#!/bin/sh

# Check if the user passed the name of the plugin as a parameter
if [ "$#" -ne 1 ]; then
    echo "Error: This script requires exactly one parameter."
    exit 1
fi

plugin_name="$1"

# Get the full path to the script
script_path="$(realpath "$0")"
# Extract the directory path
script_dir="$(dirname "$script_path")"
# Create the repository directory
repo_path="$script_dir"/"$plugin_name"
mkdir "$repo_path"
# Initialize a git repository
pushd "$repo_path"
git init
# Copy the plugin template files into the new repo
cp -r "$script_dir"/lib "$repo_path"
cp "$script_dir"/src/esbuild.js "$repo_path"
cp "$script_dir"/src/pre-commit "$repo_path"/.git/hooks
cp "$script_dir"/src/README.md "$repo_path"
cp "$script_dir"/.gitignore "$script_dir"/jest.config.js "$script_dir"/jsconfig.json "$script_dir"/LICENSE \
  "$script_dir"/package.json "$script_dir"/package-lock.json "$repo_path"