#!/bin/sh

# Check if the user passed the name of the plugin as a parameter
if [ "$#" -ne 1 ]; then
    echo "Error: This script requires exactly one parameter."
    exit 1
fi

plugin_name="$1"
echo "Creating new repository with plugin name $plugin_name..."

# Get the full path to the script
script_path="$(realpath "$0")"
# Extract the directory path
script_dir="$(dirname "$script_path")"
# Create the repository directory
repo_path="$script_dir"/"$plugin_name"

echo "Initializing repository in $repo_path..."
mkdir "$repo_path"
# Initialize a git repository
pushd "$repo_path"
git init

echo "Copying initial plugin contents..."
# Copy the plugin template files into the new repo
cp -r "$script_dir"/lib .
cp "$script_dir"/src/esbuild.js .
cp "$script_dir"/src/pre-commit ./.git/hooks
cp "$script_dir"/src/README.md .
sed -i".backup" -e "s/# Your Cool Amplenote Plugin/# $plugin_name/" ./README.md
rm ./README.md.backup
cp "$script_dir"/.gitignore "$script_dir"/jest.config.js "$script_dir"/jsconfig.json "$script_dir"/LICENSE \
  "$script_dir"/package.json "$script_dir"/package-lock.json .

echo "Installing npm dependencies..."
npm install || echo "npm install failed; might need to install node first" && exit 1
popd

echo "Success!"